# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPANPLUS-Shell-Curses
version:      0.06
version_from: lib/CPANPLUS/Shell/Curses.pm
installdirs:  site
requires:
    CPANPLUS:                      0.045
    Curses::UI:                    0.87
    Cwd:                           0
    File::chdir:                   0
    File::Spec:                    0
    Module::ScanDeps:              0
    Pod::Text:                     0
    Test::Pod:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
